### PR TITLE
Add ng-repeat for ideas display on index.html

### PR DESCRIPTION
**Pull request by annekef**
Using hardcoded data for now. The basic template for each idea is now set and ready to be populated by future db data.

### CODE REVIEW

**Comment by millionhari** [comment]
screen shot 2015-03-16 at 3 00 10 pm

**Comment by millionhari** [comment]
screen shot 2015-03-16 at 3 00 43 pm

**Comment by KalevRK** [comment]
Looks great! Glad that we can mock up ideas on the front-end without having to make requests to the server.

**Comment by millionhari** [comment]
Approved because this pull request is awesome

**Pull request merged**
