### PR TITLE
(bugfix) Revert back to previous pull request

### PR DESCRIPTION
**Pull request by millionhari**
Reverting back to Anneke's pull request

### CODE REVIEW

**Comment by millionhari** [comment]
Because the infinite idea post problem was only on my localhost

**Comment by annekef** [comment]
I think there were some server-side commits after my last pull request that we may want to keep. Let's discuss in/after SCRUM!

**Comment by annekef** [comment]
Okay, so this looks like it doesn't touch the server-side stuff, in fact. Green light from me!

**Comment by Rudimental** [comment]
Looks good from here!

**Pull request merged**
